default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  password: postgres

development:
  <<: *default
  database: volt-blog_development

test:
  <<: *default
  database: volt-blog_test

production:
  <<: *default
  database: volt-blog_production
  username: volt-blog
  password: <%= ENV['VOLT-BLOG_DATABASE_PASSWORD'] %>
